ruby_version: "ruby-2.1.2-p0"
bundler_version: "1.7.12"

notify:
- channel: email
  trigger-on: failed
  branch: master*
  message: "Congratulations, testing of %repo%'s %branch% branch finished in %duration% with %error-count% error(s) and %passed-count% success(es)"
  recipients: asaichuk@solanolabs.com
  body: "custom body"

- channel: email
  trigger-on: status-changed
  branch: master*
  message: "Status-changed Congratulations, testing of %repo%'s %branch% branch finished in %duration% with %error-count% error(s) and %passed-count% success(es)"
  recipients: asaichuk@solanolabs.com