ruby_version: "ruby-2.0.0-p643"
bundler_version: "1.11.2"
plan:
  - first
  - manual_approval
  - third
coverage:
  version: 2
  enabled: true
profiles:
  first:
    coverage:
      version: 2
      enabled: true
      ratchet: 10
    test_pattern:
      - spec/models/csv_parser_spec.rb
  manual_approval:
    approvers:
      - test1@example.com
      - test2@example.com
      - test3@example.com
  third:
    test_pattern:
      - spec/models/csv_parser_spec.rb
