ruby_version: "ruby 2.3.0p0"
bundler_version: "1.16.1"
plan:
  - first
  - manual_approval
  - second
profiles:
  first:
    test_pattern:
      - spec/models/**_spec.rb
  manual_approval:
    recipients:
      - "admin@example.com"
  second:
    test_pattern:
      - spec/models/**_spec.rb
