ruby_version: "ruby-2.0.0-p643"
bundler_version: "1.11.2"

notify:
- channel: email
  trigger-on: done
  branch: master*
  message: "bbbbbbbb"
  recipients: asaichuk@solanolabs.com
  body: "aaaaaaaaaaaaaaaaaaaaaaaaaaaa"

rerun_list:
  - spec/models/csv_parser_spec.rb
