ruby_version: "ruby-2.4.0"
bundler_version: "1.15.4"

plan:
- first
- second

profiles:
  fetch:
    script: bin/fetch

  first:
    agent: agent2
    script: bin/first
    output:
      - out.tar

  second:
    agent: emcee
    test_pattern:
      - spec/models/**_spec.rb
