ruby_version: "ruby-2.0.0-p643"
bundler_version: "1.11.2"

plan:
  - default
  - js

profiles:
  default:
    test_pattern:
      - spec/**_spec.rb
  js:
    tests:
      - bundle exec rake jasmine:ci

coverage:
  version: 2
  enabled: true
