ruby_version: "ruby-2.0.0-p643"
bundler_version: "1.11.2"
plan:
  - default
coverage:
  version: 2
  enabled: true
profiles:
  default:
    coverage:
      version: 2
      enabled: true
      ratchet: 10
    test_pattern:
      - spec/models/csv_parser_spec.rb
