ruby_version: "ruby-2.0.0-p643"
bundler_version: "1.11.2"

notify:
- channel: email
  trigger-on: failed
  branch: master*
  message: "Fail"
  recipients: asaichuk@solanolabs.com
  body: "custom"

- channel: email
  trigger-on: failed
  branch: master*
  message: "Fail w/o body"
  recipients: asaichuk@solanolabs.com
