ruby_version: "ruby-2.4.0"
bundler_version: "1.15.4"

plan:
- first
- second

profiles:
  first:
    test_pattern:
      - spec/models/**_spec.rb

  second:
    test_pattern:
      - spec/models/**_spec.rb
