plan:
- first
- second

profiles:
  fetch:
    script: bin/fetch

  first:
    agent: agent2
    script: bin/first
    output:
      - out.tar

  second:
    agent: stage2
    test_pattern:
      - spec/models/**_spec.rb
